### ISSUE TITLE
Symbol's function definition is void: org-html-format-headline--wrap

### ISSUE THREAD

**Issue by nblumoe** [yjwen/org-reveal#102]
When trying to export I get the above error message. This seems to be an issue with changed function names in ox-html for org mode 8.3beta

This issues also occurred in org-impress-js and was fixed like this: https://github.com/kinjo/org-impress-js.el/pull/8/commits
I hope these commits help solving this easily.

My Versions:
Org-mode version 8.3beta (release_8.3beta-797-ga5c456 @ [...])
GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org
Mac OSX 10.10.2

**Comment by yjwen** [comment]
Oops. I didn't find out how to get Org-mode 8.3beta. Could you please tell me where to get a 8.3beta package?

**Comment by nblumoe** [comment]
Sure @yjwen, clone it from github and use that.

Instructions: http://orgmode.org/manual/Installation.html

**Comment by yjwen** [comment]
OK, I never realize the Org-mode git repository has a version defined. :)

I've tried the latest Org-mode git version (8.3beta) with org-reveal's master branch. The Readme.html was generated without error.

Can you please send me a sample Org document that can reproduce the issue?

Regards,
Yujie

**Comment by nblumoe** [comment]
This is happening with the included README.org, too. Can be used to reproduce it.

I tracked this down a bit more based on what you said. It's true, this fix is included in the master branch, but it's not in the ELPA package ox-reveal-20150206.708
Would be cool if you could push an update to ELPA.

**Comment by yjwen** [comment]
The API of 8.3 Org-mode is different from the 8.2x version. To solve the API mismatching problem, org-reveal has two branches, "stable" for 8.2x Org-mode and "master" for 8.3x ones.

MELPA ox-reveal, the "stable" branch, is expected to be used with ELPA org-mode, currently a 8.2x one. So I cannot put the fix into MELPA. Otherwise, those who are using MELPA ox-reveal with ELPA org-mode will experience API errors.

If you are using 8.3x Org-mode, please pull the master branch of org-reveal from github directly. :)
