### ISSUE TITLE
ignore tags

### ISSUE THREAD

**Issue by psifertex** [yjwen/org-reveal#106]
Is there a way to ignore org-mode tags? Right now when I add a tag to a header, the content is shown on the slide.

**Comment by yjwen** [comment]
Hi,

  Currently there is no instant trick to disable exporting tags of a header. But you can hide tags by defining a custom CSS.

  Say if your headings are tagged `:work:` as below:

    * Heading 1 :work:
      Blabla.
  
  Then you can specify a custom CSS file by adding `#+REVEAL_EXTRA_CSS: ./hidden.css` to your Org document.

    #+REVEAL_EXTRA_CSS: ./hidden.css
    * Heading 1 :work:
      Blabla.

  Then prepare the hidden.css with the following contents:

    .reveal .work { visibility: hidden; }

  If there are other tags, add more similar lines with `.work` changed to other tag names.

  Make sure the hidden.css is placed in the same directory of the exported HTML file. Then open the HTML, you should see the expected tags are hidden.

Regards,
Yujie

**Comment by psifertex** [comment]
Thanks! I've used some custom css to tweak a few other things, should have thought about it for that. Much appreciated.

**Comment by fooqri** [comment]
Just a quick note if others are trying to customize content for reveal output. An alternative approach that worked for me was to set up a macro in the org doc. This could similarly be added as a function in .init instead of as a macro, in that case setting the org-export-exclude-tags. In these examples :mdignore: is a tag to hide heading from markdown export, :revealignore: will hide heading on reveal export.


Setup global tags in .init.el that hide headlines when exporting.
```
(defun ignored-headlines-removal (backend)
  "Remove all headlines with tag ignore_heading in the current buffer.
     BACKEND is the export back-end being used, as a symbol."
  (cond ((org-export-derived-backend-p backend 'md) (setq  org-export-exclude-tags '("noexport" "mdignore"))) ((org-export-derived-backend-p backend 'reveal) (setq  org-export-exclude-tags '("noexport" "revealignore") ))) 
 )

(add-hook 'org-export-before-parsing-hook 'ignored-headlines-removal)
```

## Use Macros to customize exports in a specific document.
```
#+MACRO: tags-on-export (eval (format "#+EXCLUDE_TAGS: %s" (cond ((org-export-derived-backend-p org-export-current-backend 'md) "mdignore") ((org-export-derived-backend-p org-export-current-backend 'reveal) "revealignore"))))
```

## hide toc for reveal export
```
#+MACRO: toc-on-export (eval (format "%s" (cond ((org-export-derived-backend-p org-export-current-backend 'md) "#+OPTIONS: toc:1") ((org-export-derived-backend-p org-export-current-backend 'reveal) "#+OPTIONS: toc:nil"))))
{{{toc-on-export}}}
```

## hide tags for reveal export
```
#+MACRO: tags-on-export (eval (format "%s" (cond ((org-export-derived-backend-p org-export-current-backend 'md) "#+OPTIONS: tags:1") ((org-export-derived-backend-p org-export-current-backend 'reveal) "#+OPTIONS: tags:nil"))))
{{{tags-on-export}}}
```
