### ISSUE TITLE
Paragraph fragmentation does not work

### ISSUE THREAD

**Issue by gjasny** [yjwen/org-reveal#107]
Hello,

today I updated to `20150325.2313` from MELPA and paragraph fragmentation seems to be broken.

```
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+options: num:nil toc:nil

** Fragmented Contents

    Make contents fragmented (show up one-by-one) by setting option
    =ATTR_REVEAL= with property ":frag frag-style", as illustrated
    below.

#+ATTR_REVEAL: :frag roll-in
    Paragraphs can be fragmented.
```

Thanks,
Gregor

**Comment by yjwen** [comment]
It is due to I recently merged master into stable branch so as to add new features into MELPA's ox-reveal. But accidentally overwritten the codes for marking fragment for paragraphs.

Sorry for the inconvenience. I've just update the stable branch to enable fragments on paragraphs again. Should be soon to merge into MELPA.

Regards,
Yujie
