### ISSUE TITLE
org-reveal-root shall contain 4 ////?

### ISSUE THREAD

**Issue by cnglen** [yjwen/org-reveal#144]
exporting to the single html report the error:
+ org-reveal-stylesheets: Cannot read opt/reveal.js/css/reveal.css, opt/reveal.js/css/theme/moon.css
+ (setq org-reveal-root "file:///opt/reveal.js")

It can be solved by setting (strange)
+ (setq org-reveal-root "file:////opt/reveal.js")

**Comment by yjwen** [comment]
It is due to different local file URL by OS types.
In Windows, the local file URL is like `file:///c:/org-reveal`, so the `file:///` is removed to extract the file path `c:/org-reveal`.
But in Linux-like OS, it is `file:///home/yj/org-reveal` and only `file://` should be removed.

Just fix the bug. Please try the latest master branch.

Regards,
Yujie
