### ISSUE TITLE
Stacking up fragments

### ISSUE THREAD

**Issue by fpopineau** [yjwen/org-reveal#161]
Hi,

Org-Reveal is very nice. I'd like to suggest adding a feature, namely the ability to stack up fragments like this:

#+attr_html: :width 400px :height auto :style position: relative; top: 0; left: 0;
#+attr_reveal: :frag fade-out :frag_idx 2
#+attr_reveal: :frag appear :frag_idx 1
[[some link to some image]]

Reveal.js should allow to make the image appear and then fade out.
What do you think ?

Thanks a lot for org-reveal !

**Comment by yjwen** [comment]
Hi,

I've been thinking of a way to support multiple fragments for a while. Technically it is possible, but it requires either some hacking into the HTML exporter's code, or a lot of code change to org-reveal.

There is another way to gain finer controls on fragments, by embedding HTML codes into Org text directly. Yes it is kind of low-level operation, but powerful.

To apply "fading-out" effect on any part of an Org document, just surround the text by HTML tag `<span class="fragment fade-out">` and `</span>`, using the Org-mode's embedded quoting syntax `@@html:`.

For example, the following Org text shows how to fade out parts of a paragraph, and list items.
```org
* Slide 1
  #+ATTR_REVEAL: :frag fade-in
  @@html:<span class="fragment fade-out">@@Text 1@@html:</span>@@ and
  @@html:<span class="fragment fade-out">@@Text 2@@html:</span>@@.

  #+ATTR_REVEAL: :frag (fade-in)
  * @@html:<span class="fragment fade-out">@@Item 1@@html:</span>@@
  * @@html:<span class="fragment fade-out">@@Item 2@@html:</span>@@
```
Unfortunately, `@@html` doesn't work well with pictures. To let a picture fade out, please use `#+HTML` directive for the **fading in** effect, and `#+ATTR_REVEAL` for the **fading out** one, as the following example illustrates:
```org
* Slide 1

  #+HTML:  <span class="fragment fade-in">
  #+ATTR_REVEAL: :frag fade-out
  [[./hlevel.png]]
  #+HTML: </span>
```

So, due to the fact that:

1. It is complicated to support multiple fragments by org-reveal,
2. Multiple fragments can be done by Org-mode's quoting syntax.
3. I assume the requirement for multiple fragment is not common.

Please let me conclude the issue by suggestion of embedding raw HTML contents by Org-mode's quoting syntax.

Regards,
Yujie

**Comment by AdrieanKhisbe** [comment]
@fpopineau To ease creation you could use an org macro:

```
#+MACRO: fadeout  @@html:<span class="fragment fade-out">@@ $1 @@html:</span>@@
#+ATTR_REVEAL: :frag (fade-in)
  * {{{fadeout(Item 1)}}}
  * {{{fadeout(Item 2)}}}
```

**Comment by fpopineau** [comment]
2017-10-20 18:38 GMT+02:00 Adrien Becchis <notifications@github.com>:

> @fpopineau <https://github.com/fpopineau> To ease creation you could use
> an org macro:
>
> #+MACRO: fadeout  @@html:<span class="fragment fade-out">@@ $1 @@html:</span>@@
> #+ATTR_REVEAL: :frag (fade-in)
>   * {{{fadeout(Item 1)}}}
>   * {{{fadeout(Item 2)}}}
>
>
Nice idea !

Thanks,
