### ISSUE TITLE
Unable to set #+REVEAL_TITLE_SLIDE_TEMPLATE

### ISSUE THREAD

**Issue by drorata** [yjwen/org-reveal#209]
I'm trying define the title slide within the org buffer. I tried to have buffer local variable for vain. I also tried the #+REVEAL_TITLE_SLIDE_TEMPLATE but it didn't work. How can I utilize this option?

**Comment by yjwen** [comment]
You can set option `reveal_title_slide` to a template string.

```
#+OPTIONS: reveal_title_slide:"<h1>TheTitle</h1>"

* Slide 1
  
  The contents.
```

Note that there cannot be spaces in the template string. To specify a template string with spaces, please set variable `org-reveal-title-slide` to that string value.

**Comment by drorata** [comment]
This didn't work. Adding your suggestion yielded the following error:

`org-reveal-template: Wrong number of arguments: #[(info) "ÂÃÄÅ\"\"BÆÃÄÇ\"\"BÈÃÉ!\"BÊËÄÌ\"!BÍÃÄÎ\"\"BÏÐÑÒÄÓ\"Ô\"Õ#BÖÄ×\"BØÄÙ\"ËÄÌ\"	RÚÛ	!8\")BÜÄÝ\"^ÞB¯	" [info file 116 org-export-data plist-get :title 115 :subtitle 100 org-export-get-date ...] 13 ("/Users/user/.emacs.d/elpa/org-plus-contrib-20160606/ox-html.elc" . 61276)], 0`

In addition, can you also explain how to use the variable `org-reveal-title-slide` as a buffer local variable?

**Comment by yjwen** [comment]
Are you using the ox-reveal from MELPA or from the github repository?

**Comment by drorata** [comment]
It is installed through MELPA.

**Comment by yjwen** [comment]
Hi,

  Sorry for such a late reply. 

  Since you are using the MELPA version, which is the "stable" branch of GitHub org-reveal, the way of setting title slide is different from the master branch.

  For MELPA versions prior to July, 2016, please use the option line `#+REVEAL_TITLE_SLIDE_TEMPLATE` to control the content of the title slide. For example:
```
#+REVEAL_TITLE_SLIDE_TEMPLATE:<h5>My Title</h5>
#+REVEAL_TITLE_SLIDE_TEMPLATE:<h1>My Name</h1>

* Head 1
  Content 1.
```

 You can use escaping characters in the template string to retrieve informations from your document. `%t` for title, `%a` for author, `%e` for email address, `%d` for export date.

  For MELPA versions from July, 2016 (the one I just merged from the master branch), please refer to https://github.com/yjwen/org-reveal#set-the-title-slide for a detail description.

Regards,
Yujie
