### ISSUE TITLE
org 9.2 compatibility issue on ox-reveal.el

### ISSUE THREAD

**Issue by breadncup** [yjwen/org-reveal#363]
org 9.2 warning for ox-reveal:

Warning (org): 
Please update the entries of `org-structure-template-alist'.

In Org 9.2 the format was changed from something like

    ("s" "#+BEGIN_SRC ?\n#+END_SRC")

to something like

    ("s" . "src")

Please refer to the documentation of `org-structure-template-alist'.

The following entries must be updated:

(("n" "#+BEGIN_NOTES\n?\n#+END_NOTES"))

The #+BEGIN_NOTES is being used in ox-reveal and this must be updated.

Thank you,

**Comment by breadncup** [comment]
```
  ;; Register auto-completion for speaker notes.
  (when org-reveal-note-key-char
    (add-to-list 'org-structure-template-alist
                 (list org-reveal-note-key-char "#+BEGIN_NOTES\n\?\n#+END_NOTES")))

```
needs to be updated as

```
  ;; Register auto-completion for speaker notes.
  (when org-reveal-note-key-char
    (add-to-list 'org-structure-template-alist
                 (cons org-reveal-note-key-char "NOTES")))
```

**Comment by jmhammond** [comment]
Unfortunately, development on this repository seems to have been abandoned a long time ago.

**Comment by lechten** [comment]
FYI: I opened a PR to include [org-re-reveal](https://gitlab.com/oer/org-re-reveal) into MELPA: https://github.com/melpa/melpa/pull/5989

I do not recommend to use that yet, because I'm not sure that the current naming and repository will survive, which depends on feedback that I might receive for MELPA...

**Comment by jmhammond** [comment]
@lechten I'll keep my eye on it. If it gets accepted, I'll submit my pull request regarding org-ref #338 over to your repository. Good luck! 👍

**Comment by carlosgeos** [comment]
https://github.com/melpa/melpa/pull/5989#issuecomment-459890924 time to switch to `org-re-reveal` !!

**Comment by lechten** [comment]
Yes,`org-re-reveal` has been accepted into MELPA, works for me, will continue there.

@jmhammond Thanks for the thumbs up, contributions are very welcome. Note, however, that in [emacs-reveal](https://gitlab.com/oer/emacs-reveal) I use a different mechanism to generate bibliography slides ("normal" slide with printbibliography command), which also exports nicely to LaTeX/PDF. This issue does not appear to be the proper place for that discussion, though.

**Comment by breadncup** [comment]
Thank you for filing the bug to ELPA and fix it. I'm not familiar with the process though, I'm pleased that it's fixed. Thanks!

**Comment by phillord** [comment]
@lechten I'm not sure that this is the best way of handling things, except as a temporary fix. Having two very similar packages with different names is just going to cause confusion. Would it not make more sense to offer taking over maintainership from @yjwen if they do not want to continue?

**Comment by lechten** [comment]
@phillord How could that happen?

These are my failed attempts at cooperation:
- https://github.com/melpa/melpa/pull/5901
- yjwen/org-reveal#277
- yjwen/org-reveal#349

**Comment by phillord** [comment]
@lechten Well, you've already created two versions. I agree that you've attempted contact. So, why not announce that you are taking maintainership as this is unmaintained, probably here and on the org-mode mailing list. Give it a few weeks to see if any one objects. But take this repo *as is*, rather than renaming it and try and update MELPA to your repository.

As it is, there will be many users of org-reveal who will have it installed and who will not know that org-re-reveal exists. And in a years time, you will not have a package called "org-re-reveal" a name which won't really make sense.

**Comment by lechten** [comment]
1. How do I take a repo as is? In my view that should not be possible.
2. In my view the name org-re-reveal acknowledges its origin, now and in the future.

Thanks for pointing out the org-mode mailing list. As I do not understand the first point above and we disagree concerning the second one, for the time being I won't post an announcement for org-re-reveal.

**Comment by phillord** [comment]
In answer to 1. clone it and do not change the name. And 2. yes, it does but it requires users to remove org-reveal and install org-re-reveal; what value acknowledging its origin?

Advantages of my approach: doesn't require the user to do anything for uninterrupted slide presentation. Disadvantages of my approach: you take over a namespace that could already been seen as taken, which might be seen as hostile. If this happens and @yjwen  returns, a discussion would need to be had, but if you don't change the name merging the two code bases would be eas(ier) to merge.

Of course, you are free to do with your time as you see fit, so no problems either way (and I will be pleased to see org-(re)-reveal maintained. If you are unsure, you could always take a straw poll on the org-mode mailing list.

**Comment by lechten** [comment]
I maintained my fork under the original name between April 2017 and end of 2018. I had to change the name for inclusion in MELPA (the story evolved from https://github.com/melpa/melpa/pull/5901 over https://github.com/melpa/melpa/pull/5979 to https://github.com/melpa/melpa/pull/5989).

I did not try this, but it should be possible to have both versions installed at the same time without the need to remove org-reveal (otherwise, there is a bug in org-re-reveal).

**Comment by joonro** [comment]
I just installed `org-re-reveal`, and I found there are some inconsistencies such as using `r` instead of `R` for export shortcut which made it conflict with reStructuredText export. And I have many elisp clickable links which calls `org-reveal-export-to-html` with my settings on documents, and I have to change them to `org-re-reveal-export-to-html` as well (maybe I should create a wrapper function so I can chaege which function I want to use easily). Also the exported html slides were broken for some reason so I revert back to the `org-reveal` for now.

I hope what @phillord is suggesting is possible, but I'm sure it will be a lot of work for @lechten so I'm just glad at least this great package is being maintained in some way. Thanks!

**Comment by phillord** [comment]
No, I don't think you did have to change the name for MELPA. What @purcell said was that he didn't want two packages with a nameclash. But the best solution was to become co-maintainer. This way you've made all the PRs unusable. @kidd noted the same thing. And @gahag said "let's put a time limit" on responses from @yjwen. I still think forking this repo unchanged, and asking MELPA to move the location for the existing package is much cleaner.

Anyway, I shall end it there, as I see you have been down this path and may not wish to reconsider. Regardless of your decision, thanks for picking up the package.

**Comment by lechten** [comment]
@joonro Thanks for trying! I changed the key binding in an afterthought without proper research. Indeed, "r" conflicts with RSS export as well. I opened an [issue](https://gitlab.com/oer/org-re-reveal/issues/4) for this.

In elisp, occurrences of "org-reveal-" have to be replaced with "org-re-reveal-".

**Comment by lechten** [comment]
@phillord When you cited the time limit by @gahag you did not mention that the suggestion was "next monday", which passed without reaction. I feel offended by this omission.

**Comment by phillord** [comment]
@lechten My apologies, I had no desire to cause offense. @purcell possibly just missed it. He didn't say no either. Anyway, I mean to leave the issue at my last comment, but didn't want to go out leaving you feeling offended. So, again, thanks for being willing to take up the package.

**Comment by joonro** [comment]
@lechten Thank you! Yes it would be great if the keybinding changed back to `R`. Should I report any issues to the repo at [gitlab](https://gitlab.com/oer/org-re-reveal/) from now on?

**Comment by lechten** [comment]
@joonro Yes, issues at gitlab are welcome.

I want to allow parallel installations of org-re-reveal and org-reveal. Thus, they must use different keys. I've [written to the Org mode mailing list](https://lists.gnu.org/archive/html/emacs-orgmode/2019-02/msg00093.html) regarding this.

**Comment by lechten** [comment]
Let me clarify my position. This is not my repository, neither is org-reveal at MELPA my creation. Taking either over requires a personality different from mine.

Currently, org-re-reveal suffers from a typical issue: I'm the only developer. I spend time on activities that I may deem more important than maintaining a repository, likely with weeks of absence. I might loose interest entirely. I will certainly not be around forever. [I opened an issue](https://gitlab.com/oer/org-re-reveal/issues/6) to address this.

**Comment by purcell** [comment]
Look, if lots of people are going to have to start using `org-re-reveal`, and @yjwen is completely unresponsive, then we should probably just change the MELPA `org-reveal` package recipe to point at a fork or otherwise-actually-maintained version, ideally owned by an organisation with more than one member. I'm not really in a position to judge whether this is the case, but I'm open to any plan you can all agree on.

**Comment by yjwen** [comment]
Hi, guys,

  Sorry for being on missing list for such a long time. Got busy at jobs. For the 9.2 compatibility issue, I have merged the pulling request. Should be OK for the next MELPA update.

Regards,
Yujie

**Comment by yjwen** [comment]
Code has been merged. Thanks for all you dear friends for helping resolving the issue.
