### ISSUE TITLE
Can't export to single_file anymore?

### ISSUE THREAD

**Issue by gugutz** [yjwen/org-reveal#395]
My PDF suddently stopped compiling.

After a lot of time removing sections from my org file to see what was causing it, i isolated the problem to a single line, the line that tells org-reveal to export to single_file.

Is this a bug or was it actually removed from org-reveal?
IMO it is one of the biggest conveniences since you don't have to carry along all the images with the html file.

**Comment by rbino** [comment]
I've just stumbled upon this - it seems that reveal.js 3.8.0 has removed `lib/js/head.min.js` since it doesn't use it anymore, but org-reveal (or more precisely [ox-reveal](https://github.com/hexmode/ox-reveal/blob/master/ox-reveal.el#L477)) is still looking for it, and it fails if doesn't find it.

The quick workaround is using reveal.js 3.7.0, but probably this needs to be fixed in ox-reveal.

**Comment by gugutz** [comment]
I actually checked and was using the latest version of org-reveal when the issue occurred
It still happens when i try to export to single file.
Would be great to have this feature back, though.

**Comment by yjwen** [comment]
Hi, @gugutz 

I checked locally with an sample org file with images, the exporting to single file works well. Are you using the MELPA ox-reveal? And what is the reveal.js version?

**Comment by yjwen** [comment]
Close for now. If this issue still exists, please feel free to reopen it.
