### ISSUE TITLE
Warning about obsolete export option for sub-trees?

### ISSUE THREAD

**Issue by Knusper** [yjwen/org-reveal#420]
What about this warning the user gets when exporting with `R` `S` only the current sub-tree?
Using simply the option `C-s` to change the scope to the sub-tree and running `R` `R` does **not** produce the same result.

**Comment by yjwen** [comment]
Yes. The `R` `S` options has being set obsolete for a long while, as `C-s` `R` `R` is doing the same thing. Maybe it is the time to remove it now.

**Comment by Knusper** [comment]
It is not doing the same thing for me. I will post the output later today.

**Comment by Knusper** [comment]
```
E.g. conisder this subtree

#+TITLE:  Functions in Python
#+AUTHOR: Knusper
#+EMAIL:  spam@spam.com
#+OPTIONS: num:nil toc:1 timestamp:nil email:t
#+REVEAL_THEME: moon
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_HLEVEL: 2
#+REVEAL_INIT_OPTIONS: progress:false

*** Positional- & keyword parameters
    
    Positional:
    #+begin_src python
      def function_name(p1, p1, p3, ...):
    #+end_src
    Keyword:
    #+begin_src python
      def height(v0, t, g=9.81):  
	  return v0*t - 0.5*g*t**2
    #+end_src
    Keyword parameters are used for defining a function with default
    parameters.
```

And here is the diff between the html file from `C-s RR` and `RS`:

```
@@ -2,7 +2,7 @@
 <html lang="en">
 <head>
 <meta charset="utf-8"/>
-<title>Positional- &amp; keyword parameters</title>
+<title>Functions in Python</title>
 <meta name="author" content="(Edmund Christian Herenz)"/>
 <style type="text/css">
 .underline { text-decoration: underline; }
@@ -26,8 +26,9 @@
 <body>
 <div class="reveal">
 <div class="slides">
-<section id="sec-title-slide"><h1 class="title">Positional- &amp; keyword parameters</h1><h2 class="author">Edmund Christian Herenz</h2><h2 class="email"><a href="mailto:eherenz@eso.org">eherenz@eso.org</a></h2>
-</section>
+<section>
+<section id="slide-orga0f71a0">
+<h2 id="orga0f71a0">Positional- &amp; keyword parameters</h2>
 <p>
 Positional:
 </p>
@@ -49,6 +50,8 @@
 Keyword parameters are used for defining a function with default
 parameters.
 </p>
+</section>
+</section>
 </div>
 </div>
 <script src="https://cdn.jsdelivr.net/npm/reveal.js/js/reveal.js"></script>
```

**Comment by yjwen** [comment]
I see. It looks `C-s R R` is not working the right way. The sections are messed up. `R S` should be the expected behavior. Let me remove the misleading warning at first.

**Comment by Knusper** [comment]
Just for reference, I use orgmode version 9.3.6

**Comment by yjwen** [comment]
It is strange that `C-s R R` is not working right. There are obvious mismatched `</section>` tags in the exported HTML. I remember it was working right before. Let me check what is wrong there.

**Comment by yjwen** [comment]
Found the difference. It is due to the different "cropping" methods used by org-mode's sub-tree export (`C-s R R`) and org-reveal's (`R S`).

Take the following org file as an example.
```
#+TITLE:  The Title

* Heading 1
Contents of heading 1

* Heading 2
Contents of heading 2

** Sub-heading 2.1
Contents of heading 2.1
```
org-mode's sub-tree export on `Heading 2` is equivalent to "cropping" the file to:
```
#+TITLE: Heading 2

Contents of heading 2

* Sub-heading 2.1
Contents of heading 2.1
```
and then export as normal.

The problem is the orphan `Contents of heading 2`, which is under no heading. org-reveal didn't recognize the orphan contents.  Unless the contents of heading 2 is empty, there will be unmatched `</section>` tags in the exported HTML. It is an known issue.

While org-reveal's sub-tree export is equivalent to "cropping" the file to
```
#+TITLE:  The Title

* Heading 2
Contents of heading 2

** Sub-heading 2.1
Contents of heading 2.1
```
and export.

There will be no orphan contents and the sub-heading 2.1 remains the level-2 heading. No syntax error in the exported HTML either.

It should be the user to determine which way to use.
