### ISSUE TITLE
The script in exported document gives error: SyntaxError: expected property name, got ','

### ISSUE THREAD

**Issue by SebastianCallh** [yjwen/org-reveal#428]
The exported script tag does not contain valid JS when exporting a plain document (no reveal configurations) after a clean install for me. https://ibb.co/GWcBcx4 

It looks like this line only creates a comma which breaks the JS syntax. https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L716

**Comment by ezeaguerre** [comment]
Same thing here! I was trying it for the first time and bumped into this.

Maybe the assignment of `reveal-4-plugin` is wrong, instead of defaulting to `(car "" "")` should default to `nil` so that `if-format` can skip it. But I'm using version 4 already, I don't know why it doesn't work, maybe it's because I'm using the version from the CDN.

Anyway, I added the following to the top of my file and everything worked fine:

```
#+REVEAL_REVEAL_JS_VERSION: 4
```

**Comment by yjwen** [comment]
Yes. @ezeaguerre is right. It should be `(cons nil nil)`. Fixed. Thanks.
