### ISSUE TITLE
Confusing multiplexing documentation

### ISSUE THREAD

**Issue by baracunatana** [yjwen/org-reveal#429]
The documentation for multiplexing don't seem to be up to date with reveal 4.0.

Since multiplexing is now a separate plugin and isn't included in the core release of reveal.js, you now have to include it as an external plugin. The issue is that, according to https://github.com/reveal/multiplex#multiplex-plugin, you have to load different .js files for master and client presentations.

How can multiplex be loaded correctly from org-reveal?

**Comment by yjwen** [comment]
Fixed. Multiplexing exports and document updated with reveal.js 4.0

**Comment by JoeOsborn** [comment]
It looks like this commit removed the `(defvar client-multiplex nil)`.  Is that correct?  I see the name is bound in a `let*` but I saw an error when I updated to the latest melpa release due to this variable not being defined (fixed by putting the defvar back).  Could it be a lexical vs dynamic scoping issue?  I'm not expert in elisp by any means.

**Comment by yjwen** [comment]
@JoeOsborn Were you using C-c C-e R R to export when you saw the error?

**Comment by JoeOsborn** [comment]
I use ox-reveal as part of an org-publish pipeline in batch mode.  The publish function I’m using is org-reveal-publish-to-reveal.

**Comment by yjwen** [comment]
Let me check whether org-reveal-publish-to-reveal should be updated too.

**Comment by yjwen** [comment]
Done. Should be working with org-publish now.
