### ISSUE TITLE
How to enable default fragmenting for a list

### ISSUE THREAD

**Issue by nbren12** [yjwen/org-reveal#49]
Is there a way to enable fragmenting for a list using the default style (e.g. fade in)? Something like this would be nice:

```
#+ATTR_REVEAL:  :frag default
- Item 1
- Item 2
- Etc.
```

**Comment by lvh** [comment]
Hi nbren12; did you figure out how to do this?

**Comment by yjwen** [comment]
Please refer to https://github.com/yjwen/org-reveal#list-fragments

**Comment by lvh** [comment]
@yjwen Thanks! Looks like my question is *slightly* different though. I want to accomplish two things:

1. Every list is fragmented by default.
2. I can configure the default fragment style somewhere (e.g. `roll-in`).

**Comment by yjwen** [comment]
OK, I see.

For item 1, I can add default fragment style for list, but I'd prefer not to specialize list from other Org elements and leave the default fragment style problem to CSS/JS.

For item 2, I think it is a reasonable request, let me add the feature to org-reveal.

**Comment by yjwen** [comment]
Updated. Please refer to https://github.com/yjwen/org-reveal#fragment-styles

**Comment by djelenc** [comment]
I apologize for resurrecting this question, but to make it clear: can point 1 in @lvh's question be achieved, that is, can I set a global option so that all lists in a document get fragmented?

And if possible, can I then set for a specific list to not be fragmented?

Kind of the opposite as it is now where lists are by not fragmented by default, but I can specify fragmentation for a specific list?
